let sorcerer = {};

sorcerer["Trunk Data"] = {
	["Basic"]: {
		connections: [ "Core" ],
		x: 0,
		y: 0,
	},
	["Core"]: {
		connections: [ "Defensive" ],
		requiredPoints: 2,
		x: 0.405,
		y: 1199.005,
	},
	["Defensive"]: {
		connections: [ "Conjuration" ],
		requiredPoints: 6,
		x: -1248.967,
		y: 2330.66,
	},
	["Conjuration"]: {
		connections: [ "Mastery" ],
		requiredPoints: 11,
		x: 1248.218,
		y: 2332.78,
	},
	["Mastery"]: {
		connections: [ "Ultimate" ],
		requiredPoints: 16,
		x: -1254.712,
		y: 3747.074,
	},
	["Ultimate"]: {
		connections: [ "Capstone" ],
		requiredPoints: 23,
		x: 1246.083,
		y: 3744.594,
	},
	["Capstone"]: {
		requiredPoints: 33,
		x: 209.883,
		y: 4569.17,
	},
};

sorcerer["Basic"] = {
	["Frost Bolt"]: {
		connections: [ "Basic", "Enhanced Frost Bolt" ],
		description: `{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat Effect Chance}%{/c}
{/if}Throw a bolt of frost at an enemy, dealing {c_number}{payload:IMPACT}{/c} damage and {c_important}Chilling{/c} them for {c_number}{SF_4}%{/c}.`,
		id: 0,
		maxPoints: 5,
		x: -314.79,
		y: -169.615,
	},
	["Enhanced Frost Bolt"]: {
		baseSkill: "Frost Bolt",
		connections: [ "Frost Bolt", "Flickering Frost Bolt", "Glinting Frost Bolt" ],
		description: `Frost Bolt has a {c_number}[{SF_7} * 100|%|]{/c} chance to explode on {c_important}Chilled{/c} targets, hitting surrounding enemies. Chance increased to {c_number}100%{/c} against {c_important}Frozen{/c} targets.`,
		id: 1,
		maxPoints: 1,
		x: -553.367,
		y: -301.91,
	},
	["Flickering Frost Bolt"]: {
		baseSkill: "Frost Bolt",
		connections: [ "Enhanced Frost Bolt" ],
		description: `Frost Bolt makes {c_important}Frozen{/c} enemies {c_important}Vulnerable{/c} for {c_number}{SF_9}{/c} seconds.`,
		id: 2,
		maxPoints: 1,
		x: -859.027,
		y: -329.83,
	},
	["Glinting Frost Bolt"]: {
		baseSkill: "Frost Bolt",
		connections: [ "Enhanced Frost Bolt" ],
		description: `Frost Bolt generates {c_number}{SF_10}{/c} Mana when hitting {c_important}Chilled{/c} or {c_important}Frozen{/c} enemies.`,
		id: 3,
		maxPoints: 1,
		x: -653.422,
		y: -453.325,
	},
	["Spark"]: {
		connections: [ "Basic", "Enhanced Spark" ],
		description: `{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat Effect Chance}%{/c}
{/if}Launch a bolt of lightning that shocks an enemy {c_number}{SF_2}{/c} times, dealing {c_number}{payload:PAYLOAD_PROJECTILE}{/c} damage each hit.`,
		id: 4,
		maxPoints: 5,
		x: -294.368,
		y: 167.01,
	},
	["Enhanced Spark"]: {
		baseSkill: "Spark",
		connections: [ "Spark", "Flickering Spark", "Glinting Spark" ],
		description: `Each time Spark hits, it has a {c_number}[{SF_6} * 100|%|]{/c} chance to hit up to {c_number}{SF_7}{/c} additional enemies, dealing {c_number}{payload:PAYLOAD_FORK_1}{/c} damage. If there are no other enemies to hit, Spark instead deals {c_number}[{SF_8} * 100|%|]{/c} increased damage to its primary target.`,
		id: 5,
		maxPoints: 1,
		x: -544.167,
		y: 312.77,
	},
	["Flickering Spark"]: {
		baseSkill: "Spark",
		connections: [ "Enhanced Spark" ],
		description: `Each time Spark hits an enemy it has a {c_number}[{SF_14} * 100|%|]{/c} chance to spawn a {c_important}Crackling Energy{/c}.`,
		id: 6,
		maxPoints: 1,
		x: -804.317,
		y: 359.95,
	},
	["Glinting Spark"]: {
		baseSkill: "Spark",
		connections: [ "Enhanced Spark" ],
		description: `Spark grants {c_number}[{SF_15}*100|%|]{/c} increased Critical Strike Chance per cast for {c_number}{SF_16}{/c} seconds, up to {c_number}[{SF_17}*100|%|]{/c}.`,
		id: 7,
		maxPoints: 1,
		x: -605.717,
		y: 459.955,
	},
	["Arc Lash"]: {
		connections: [ "Basic", "Enhanced Arc Lash" ],
		description: `{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat Effect Chance}%{/c}
{/if}Unleash arcing lightning that shocks enemies in front of you for {c_number}{payload:DAMAGE}{/c}. Every {c_number}{SF_10}{/c} times Arc Lash swipes, it Stuns all enemies hit for {c_number}{buffduration:STUN}{/c} seconds.`,
		id: 8,
		maxPoints: 5,
		x: 309.665,
		y: 169.14,
	},
	["Enhanced Arc Lash"]: {
		baseSkill: "Arc Lash",
		connections: [ "Arc Lash", "Glinting Arc Lash", "Flickering Arc Lash" ],
		description: `If Arc Lash's initial swipe Critically Strikes, it swipes an additional time.`,
		id: 9,
		maxPoints: 1,
		x: 571.208,
		y: 320.835,
	},
	["Glinting Arc Lash"]: {
		baseSkill: "Arc Lash",
		connections: [ "Enhanced Arc Lash" ],
		description: `Hitting a Stunned enemy with Arc Lash reduces your cooldowns by {c_number}[{SF_13}|2|]{/c} seconds.`,
		id: 10,
		maxPoints: 1,
		x: 647.288,
		y: 464.815,
	},
	["Flickering Arc Lash"]: {
		baseSkill: "Arc Lash",
		connections: [ "Enhanced Arc Lash" ],
		description: `Gain {c_number}[{SF_7}*100|%|]{/c} Movement Speed for {c_number}{SF_8}{/c} seconds per enemy hit with Arc Lash, up to {c_number}[{SF_9}*100|%|]{/c}.`,
		id: 11,
		maxPoints: 1,
		x: 871.328,
		y: 352.725,
	},
	["Fire Bolt"]: {
		connections: [ "Basic", "Enhanced Fire Bolt" ],
		description: `{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat_Effect_Chance_Script_Formula_Override:17}%{/c}
{/if}Hurl a flaming bolt, dealing {c_number}{payload:DAMAGE}{/c} damage and Burning for {c_number}{dot:BURNING}{/c} over {c_number}{buffduration:BURNING}{/c} seconds.`,
		id: 12,
		maxPoints: 5,
		x: 309.424,
		y: -168.96,
	},
	["Enhanced Fire Bolt"]: {
		baseSkill: "Fire Bolt",
		connections: [ "Fire Bolt", "Glinting Fire Bolt", "Flickering Fire Bolt" ],
		description: `Fire Bolt pierces Burning enemies.`,
		id: 13,
		maxPoints: 1,
		x: 547.598,
		y: -314.185,
	},
	["Glinting Fire Bolt"]: {
		baseSkill: "Fire Bolt",
		connections: [ "Enhanced Fire Bolt" ],
		description: `Critical Strikes with Fire Bolt increase the Burning damage the target takes by {c_number}x[{SF_11} * 100|%|]{/c} for {c_number}{buffduration:UPGRADEB_CRIT_DAMAGE}{/c} seconds.`,
		id: 14,
		maxPoints: 1,
		x: 820.993,
		y: -349.635,
	},
	["Flickering Fire Bolt"]: {
		baseSkill: "Fire Bolt",
		connections: [ "Enhanced Fire Bolt" ],
		description: `Fire Bolt generates {c_number}{SF_9}{/c} Mana when hitting a Burning enemy.`,
		id: 15,
		maxPoints: 1,
		x: 638.958,
		y: -457.985,
	},
};

sorcerer["Core"] = {
	["Charged Bolts"]: {
		connections: [ "Core", "Enhanced Charged Bolts" ],
		description: `{c_label}Mana Cost: {/c}{c_resource}{Resource Cost}{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat Effect Chance}%{/c}
{/if}Release {SF_4} bolts of lightning that course along the ground in an erratic pattern, dealing {c_number}{payload:PAYLOAD_PROJECTILE}{/c} each.`,
		id: 16,
		maxPoints: 5,
		x: 356.997,
		y: 194.845,
	},
	["Enhanced Charged Bolts"]: {
		baseSkill: "Charged Bolts",
		connections: [ "Charged Bolts", "Greater Charged Bolts", "Destructive Charged Bolts" ],
		description: `Charged Bolts gains an extra projectile.`,
		id: 17,
		maxPoints: 1,
		x: 596.883,
		y: 327.095,
	},
	["Greater Charged Bolts"]: {
		baseSkill: "Charged Bolts",
		connections: [ "Enhanced Charged Bolts" ],
		description: `Charged Bolts deals {c_number}x[{SF_27}*100|%|]{/c} increased damage to Stunned enemies.`,
		id: 18,
		maxPoints: 1,
		x: 671.203,
		y: 470.3,
	},
	["Destructive Charged Bolts"]: {
		baseSkill: "Charged Bolts",
		connections: [ "Enhanced Charged Bolts" ],
		description: `Hitting an enemy at least {c_number}{SF_31}{/c} times with Charged Bolts in a single cast reduces their damage dealt by {c_number}[{SF_32}*100|%|]{/c} for {c_number}{SF_33}{/c} seconds.`,
		id: 19,
		maxPoints: 1,
		x: 866.973,
		y: 354.415,
	},
	["Frozen Orb"]: {
		connections: [ "Core", "Enhanced Frozen Orb" ],
		description: `{c_label}Mana Cost:{/c} {c_resource}{Resource Cost}{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat Effect Chance}%{/c}
{/if}Unleash an orb that {c_important}Chills{/c} for {c_number}{SF_2}%{/c} and expels piercing shards dealing a total of {c_number}{payload:TOOLTIP_DAMAGE}{/c} damage. Upon expiration, Frozen Orb explodes, dealing {c_number}{payload:FROSTBOLT_DAMAGE}{/c} damage and {c_important}Chilling{/c} enemies for {c_number}{SF_9}%{/c}.`,
		id: 20,
		maxPoints: 5,
		x: -276.076,
		y: -213.185,
	},
	["Enhanced Frozen Orb"]: {
		baseSkill: "Frozen Orb",
		connections: [ "Destructive Frozen Orb", "Greater Frozen Orb", "Frozen Orb" ],
		description: `When cast above {c_number}{SF_28}{/c} Mana, Frozen Orb's explosion damage is increased by {c_number}x[{SF_29}*100|%|]{/c}.`,
		id: 21,
		maxPoints: 1,
		x: -451.149,
		y: -344.71,
	},
	["Destructive Frozen Orb"]: {
		baseSkill: "Frozen Orb",
		connections: [ "Enhanced Frozen Orb" ],
		description: `Frozen Orb's explosion restores {c_number}{SF_23}{/c} Mana when hitting a {c_important}Frozen{/c} enemy.`,
		id: 22,
		maxPoints: 1,
		x: -706.237,
		y: -409.725,
	},
	["Greater Frozen Orb"]: {
		baseSkill: "Frozen Orb",
		connections: [ "Enhanced Frozen Orb" ],
		description: `Frozen Orb's explosion has a {c_number}[{SF_31} * 100|%|]{/c} chance to make all enemies hit {c_important}Vulnerable{/c} for {c_number}{SF_32}{/c} seconds.`,
		id: 23,
		maxPoints: 1,
		x: -492.592,
		y: -496.78,
	},
	["Incinerate"]: {
		connections: [ "Core", "Enhanced Incinerate" ],
		description: `{c_label}Mana Cost: {/c}{c_resource}[{Resource Cost}*5] per second{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat_Effect_Chance_Script_Formula_Override:39}%{/c}
{/if}Channel a beam of fire, Burning enemies for {c_number}{payload:TOOLTIP_ONLY_DAMAGE}{/c}. Damage increases by {c_number}{payload:TOOLTIP_RAMP_DAMAGE}{/c} per second, up to {c_number}{payload:TOOLTIP_MAX_DAMAGE}{/c}.`,
		id: 24,
		maxPoints: 5,
		x: 465.318,
		y: -36.915,
	},
	["Enhanced Incinerate"]: {
		baseSkill: "Incinerate",
		connections: [ "Incinerate", "Destructive Incinerate", "Greater Incinerate" ],
		description: `While Channeling Incinerate, you take {c_number}[{SF_28} * 100|%|]{/c} less damage from Close enemies.`,
		id: 25,
		maxPoints: 1,
		x: 757.168,
		y: -63.055,
	},
	["Destructive Incinerate"]: {
		baseSkill: "Incinerate",
		connections: [ "Enhanced Incinerate" ],
		description: `While Channeling Incinerate, you burn enemies around you for {c_number}[{SF_29} * 100|%|]{/c} of the damage per second.`,
		id: 26,
		maxPoints: 1,
		x: 967.483,
		y: -164.345,
	},
	["Greater Incinerate"]: {
		baseSkill: "Incinerate",
		connections: [ "Enhanced Incinerate" ],
		description: `Incinerate now starts at full power, but its Channeling cost is increased by {c_number}[{SF_36}*100|%|]{/c}.`,
		id: 27,
		maxPoints: 1,
		x: 1011.948,
		y: -21.03,
	},
	["Fireball"]: {
		connections: [ "Core", "Enhanced Fireball" ],
		description: `{c_label}Mana Cost: {/c}{c_resource}{Resource Cost}{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat Effect Chance}%{/c}
{/if}Hurl an exploding ball of fire, dealing {c_number}{payload:PAYLOAD_PROJECTILE}{/c} damage to surrounding enemies.`,
		id: 28,
		maxPoints: 5,
		x: 227.451,
		y: -214.915,
	},
	["Enhanced Fireball"]: {
		baseSkill: "Fireball",
		connections: [ "Fireball", "Greater Fireball", "Destructive Fireball" ],
		description: `Fireball costs {c_number}{SF_17}{/c} less Mana.`,
		id: 29,
		maxPoints: 1,
		x: 403.019,
		y: -351.865,
	},
	["Greater Fireball"]: {
		baseSkill: "Fireball",
		connections: [ "Enhanced Fireball" ],
		description: `When you cast Fireball while {c_important}Healthy{/c}, it has a {c_number}[{SF_25}*100|%|]{/c} increased radius and deals {c_number}x[{SF_26}*100|%|]{/c} increased Critical Strike Damage.`,
		id: 30,
		maxPoints: 1,
		x: 408.298,
		y: -496.54,
	},
	["Destructive Fireball"]: {
		baseSkill: "Fireball",
		connections: [ "Enhanced Fireball" ],
		description: `Fireball deals {c_number}x[{SF_21} * 100|%|]{/c} increased damage to the first enemy hit by its explosion.`,
		id: 31,
		maxPoints: 1,
		x: 652.668,
		y: -422.025,
	},
	["Chain Lightning"]: {
		connections: [ "Core", "Enhanced Chain Lightning" ],
		description: `{c_label}Mana Cost: {/c}{c_resource}{Resource Cost}{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat Effect Chance}%{/c}
{/if}Unleash a stream of lightning that deals {c_number}{payload:DAMAGE}{/c} damage and chains between Nearby enemies and you up to {c_number}{SF_2}{/c} times, prioritizing enemies.`,
		id: 32,
		maxPoints: 5,
		x: 6.471,
		y: 258.33,
	},
	["Enhanced Chain Lightning"]: {
		baseSkill: "Chain Lightning",
		connections: [ "Chain Lightning", "Greater Chain Lightning", "Destructive Chain Lightning" ],
		description: `Chain Lightning bounces to {c_number}{SF_9}{/c} additional enemy.`,
		id: 33,
		maxPoints: 1,
		x: 12.326,
		y: 443.24,
	},
	["Greater Chain Lightning"]: {
		baseSkill: "Chain Lightning",
		connections: [ "Enhanced Chain Lightning" ],
		description: `Chain Lightning deals {c_number}x[{SF_10}*100|%|]{/c} increased damage per enemy hit.`,
		id: 34,
		maxPoints: 1,
		x: -165.373,
		y: 558.965,
	},
	["Destructive Chain Lightning"]: {
		baseSkill: "Chain Lightning",
		connections: [ "Enhanced Chain Lightning" ],
		description: `When Chain Lightning Critically Strikes, it has a {c_number}[{SF_11} * 100|%|]{/c} chance to spawn a {c_important}Crackling Energy{/c}.`,
		id: 35,
		maxPoints: 1,
		x: 189.963,
		y: 571.73,
	},
	["Ice Shards"]: {
		connections: [ "Core", "Enhanced Ice Shards" ],
		description: `{c_label}Mana Cost: {/c}{c_resource}{Resource Cost}{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat Effect Chance}%{/c}
{/if}Launch {c_number}{SF_3}{/c} shards that deal {c_number}{payload:IMPACT_DAMAGE_NORMAL}{/c} damage each. Deals {c_number}x[{SF_2} * 100|%|]{/c} increased damage to {c_important}Frozen{/c} enemies.`,
		id: 36,
		maxPoints: 5,
		x: -408.65,
		y: -11.405,
	},
	["Enhanced Ice Shards"]: {
		baseSkill: "Ice Shards",
		connections: [ "Ice Shards", "Greater Ice Shards", "Destructive Ice Shards" ],
		description: `Ice Shards have a {c_number}[{SF_18}*100|%|]{/c} chance to ricochet to another enemy.`,
		id: 37,
		maxPoints: 1,
		x: -703.372,
		y: -24.405,
	},
	["Greater Ice Shards"]: {
		baseSkill: "Ice Shards",
		connections: [ "Enhanced Ice Shards" ],
		description: `While you have a {c_important}Barrier{/c} active, Ice Shards treats enemies as if they were {c_important}Frozen{/c}.`,
		id: 38,
		maxPoints: 1,
		x: -945.282,
		y: -88.375,
	},
	["Destructive Ice Shards"]: {
		baseSkill: "Ice Shards",
		connections: [ "Enhanced Ice Shards" ],
		description: `Hitting an enemy with {c_number}{SF_16}{/c} Ice Shards in a single cast makes them {c_important}Vulnerable{/c} for {c_number}{SF_17}{/c} seconds.`,
		id: 39,
		maxPoints: 1,
		x: -953.972,
		y: 29.11,
	},
	["Devastation"]: {
		connections: [ "Core", "Elemental Dominance" ],
		description: `Deal {c_number}x[{SF_2} * 100|%|]{/c} increased damage to {c_important}Healthy{/c} enemies.`,
		id: 40,
		maxPoints: 3,
		x: -507.657,
		y: 206.855,
	},
	["Elemental Dominance"]: {
		connections: [ "Devastation" ],
		description: `Your damage increases over time, up to a maximum of {c_number}[{SF_3}*sLevel|%|]{/c} after {c_number}{SF_1}{/c} seconds. Casting a Skill resets this effect.`,
		id: 41,
		maxPoints: 3,
		x: -802.882,
		y: 328.45,
	},
	["Potent Warding"]: {
		connections: [ "Core" ],
		description: `Your non-Physical Damage and Resistances are increased by {c_number}[{SF_1} *100|%|]{/c}.`,
		id: 42,
		maxPoints: 3,
		x: 745.643,
		y: 149.76,
	},
};

sorcerer["Defensive"] = {
	["Flame Shield"]: {
		connections: [ "Defensive", "Enhanced Flame Shield" ],
		description: `{c_label}Cooldown:{/c} {c_resource}[{Cooldown Time}|1|]{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat_Effect_Chance_Script_Formula_Override:17}%{/c}
{/if}Engulf yourself in flames for {c_number}{buffduration:FLAMESHIELD_BUFF}{/c} seconds, Burning surrounding enemies for {c_number}{payload:AOE_DAMAGE}{/c} per second.

While Flame Shield is active, you are {c_important}Immune{/c}.`,
		id: 43,
		maxPoints: 5,
		x: -37.995,
		y: -228.055,
	},
	["Enhanced Flame Shield"]: {
		baseSkill: "Flame Shield",
		connections: [ "Flame Shield", "Mystical Flame Shield", "Shimmering Flame Shield" ],
		description: `Flame Shield grants {c_number}[{SF_13} * 100|%|]{/c} Movement Speed while active.`,
		id: 44,
		maxPoints: 1,
		x: -78.675,
		y: -402.1,
	},
	["Mystical Flame Shield"]: {
		baseSkill: "Flame Shield",
		connections: [ "Enhanced Flame Shield" ],
		description: `Enemies continue Burning for {c_number}{SF_14}{/c} additional seconds after being hit by Flame Shield.`,
		id: 45,
		maxPoints: 1,
		x: -218.94,
		y: -516.065,
	},
	["Shimmering Flame Shield"]: {
		baseSkill: "Flame Shield",
		connections: [ "Enhanced Flame Shield" ],
		description: `Flame Shield makes enemies {c_important}Vulnerable{/c} for {c_number}{SF_15}{/c} seconds.`,
		id: 46,
		maxPoints: 1,
		x: 26.33,
		y: -521.79,
	},
	["Frost Nova"]: {
		connections: [ "Defensive", "Enhanced Frost Nova" ],
		description: `{if:SF_18}{c_label}Cooldown:{/c_label} {c_resource}[{Cooldown Time}|1|]{/c} seconds
{/if}{if:SF_19}{c_label}Charges:{/c} {c_resource}{SF_2}{/c}
{c_label}Charge Cooldown:{/c_label} {c_resource}{Recharge Time}{/c} seconds
{/if}Unleash a torrent of frost, {c_important}Freezing{/c} enemies around you for {c_number}{buffduration:FREEZE}{/c} seconds.`,
		id: 47,
		maxPoints: 5,
		x: -429.64,
		y: 2.21,
	},
	["Enhanced Frost Nova"]: {
		baseSkill: "Frost Nova",
		connections: [ "Frost Nova", "Mystical Frost Nova", "Shimmering Frost Nova" ],
		description: `Frost Nova's radius is increased by {c_number}[{SF_15} * 100|%|]{/c}.`,
		id: 48,
		maxPoints: 1,
		x: -732.36,
		y: 0.7,
	},
	["Mystical Frost Nova"]: {
		baseSkill: "Frost Nova",
		connections: [ "Enhanced Frost Nova" ],
		description: `Frost Nova's {c_important}Freeze{/c} duration is increased by {c_number}[{SF_12}*100|%|]{/c} when hitting {c_number}{SF_13}{/c} or more enemies.`,
		id: 49,
		maxPoints: 1,
		x: -961.06,
		y: -59.035,
	},
	["Shimmering Frost Nova"]: {
		baseSkill: "Frost Nova",
		connections: [ "Enhanced Frost Nova" ],
		description: `Frost Nova generates {c_number}{SF_10}{/c} Mana per enemy hit.`,
		id: 50,
		maxPoints: 1,
		x: -958.045,
		y: 72.445,
	},
	["Ice Armor"]: {
		connections: [ "Defensive", "Enhanced Ice Armor" ],
		description: `{c_label}Cooldown:{/c} {c_resource}[{Cooldown Time}|1|]{/c}
A {c_important}Barrier{/c} of ice forms around you for {c_number}{buffduration:ICE_BARRIER}{/c} seconds, absorbing {c_number}[{SF_0}*100|%|]{/c} of your Base Life {c_number}({shield:ICE_BARRIER}){/c} in damage. While {c_important}Ice Armor{/c} is active, {c_number}[{SF_8}*100|%|]{/c} of your Cold Damage dealt is added to its {c_important}Barrier{/c}.`,
		id: 51,
		maxPoints: 5,
		x: -253.36,
		y: 202.875,
	},
	["Enhanced Ice Armor"]: {
		baseSkill: "Ice Armor",
		connections: [ "Ice Armor", "Shimmering Ice Armor", "Mystical Ice Armor" ],
		description: `While Ice Armor is active, your Mana Regeneration is increased by {c_number}[{SF_10} * 100|%|]{/c}.`,
		id: 52,
		maxPoints: 1,
		x: -426.975,
		y: 358.17,
	},
	["Shimmering Ice Armor"]: {
		baseSkill: "Ice Armor",
		connections: [ "Enhanced Ice Armor" ],
		description: `Enemies that hit you while Ice Armor is active have a {c_number}[{SF_12}*100|%|]{/c} chance to be {c_important}Frozen{/c} for {c_number}{buffduration:FREEZE}{/c} seconds.`,
		id: 53,
		maxPoints: 1,
		x: -661.015,
		y: 414.34,
	},
	["Mystical Ice Armor"]: {
		baseSkill: "Ice Armor",
		connections: [ "Enhanced Ice Armor" ],
		description: `While Ice Armor’s {c_important}Barrier{/c} is at or above its original amount, you deal {c_number}x[{SF_9}*100|%|]{/c} increased damage.`,
		id: 54,
		maxPoints: 1,
		x: -444.135,
		y: 493.195,
	},
	["Teleport"]: {
		connections: [ "Defensive", "Enhanced Teleport" ],
		description: `{c_label}Cooldown: {/c}{c_resource}[{Cooldown Time}|1|]{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat Effect Chance}%{/c}
{/if}Transform into lightning, becoming {c_important}Unstoppable{/c} and surging to the target location dealing {c_number}{payload:TELEPORT_DAMAGE_PAYLOAD}{/c} damage around you upon arrival.`,
		id: 55,
		maxPoints: 5,
		x: 375.285,
		y: 141.665,
	},
	["Enhanced Teleport"]: {
		baseSkill: "Teleport",
		connections: [ "Teleport", "Mystical Teleport", "Shimmering Teleport" ],
		description: `After Teleporting, take {c_number}[{SF_12}*100|%|]{/c} less damage for {c_number}{SF_13}{/c} seconds.`,
		id: 56,
		maxPoints: 1,
		x: 662.025,
		y: 258.09,
	},
	["Mystical Teleport"]: {
		baseSkill: "Teleport",
		connections: [ "Enhanced Teleport" ],
		description: `For {c_number}{buffduration:BUFF_CRACKLING_ENERGY}{/c} seconds after Teleporting, Crackling Energy deals {c_number}x[{SF_25} * 100|%|]{/c} more damage.`,
		id: 57,
		maxPoints: 1,
		x: 933.15,
		y: 263.49,
	},
	["Shimmering Teleport"]: {
		baseSkill: "Teleport",
		connections: [ "Enhanced Teleport" ],
		description: `Teleport’s cooldown is decreased by {c_number}[{SF_17}|1|]{/c} seconds per enemy hit, up to {c_number}{SF_18}{/c} seconds.`,
		id: 58,
		maxPoints: 1,
		x: 805.699,
		y: 378.73,
	},
	["Elemental Attunement"]: {
		connections: [ "Defensive" ],
		description: `Elemental Critical Strikes reduce the cooldown of your {c_important}Defensive{/c} Skills by {c_number}[{SF_1}*100|%|]{/c}. This effect cannot occur more than once every {c_number}{SF_2}{/c} seconds.`,
		id: 59,
		maxPoints: 3,
		x: -543.765,
		y: -268.415,
	},
	["Glass Cannon"]: {
		connections: [ "Defensive" ],
		description: `You deal {c_number}x[{SF_0}*100|%|]{/c} increased damage, but take {c_number}[{SF_1}*100|%|]{/c} more damage.`,
		id: 60,
		maxPoints: 3,
		x: 148.49,
		y: 365.61,
	},
};

sorcerer["Conjuration"] = {
	["Hydra"]: {
		connections: [ "Conjuration", "Enhanced Hydra" ],
		description: `{c_label}Mana Cost: {/c}{c_resource}{Resource Cost}{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat_Effect_Chance_Script_Formula_Override:20}%{/c}
{/if}Summon a {SF_3} headed hydra for {c_number}[{SF_0}|1|]{/c} seconds. Each head spits fire at a Nearby enemy, dealing {c_number}{payload:TOOLTIP_DAMAGE}{/c} damage.`,
		id: 61,
		maxPoints: 5,
		x: 376.215,
		y: -182.8,
	},
	["Enhanced Hydra"]: {
		baseSkill: "Hydra",
		connections: [ "Hydra", "Invoked Hydra", "Summoned Hydra" ],
		description: `Hydras last for an additional {c_number}{SF_15}{/c} seconds.`,
		id: 62,
		maxPoints: 1,
		x: 619.795,
		y: -308.1,
	},
	["Invoked Hydra"]: {
		baseSkill: "Hydra",
		connections: [ "Enhanced Hydra" ],
		description: `After you Critically Strike, Hydras gain {c_number}[{SF_13}*100|%|]{/c} Attack Speed for {c_number}{buffduration:MOD_ATTACK_SPEED_BONUS}{/c} seconds.`,
		id: 63,
		maxPoints: 1,
		x: 896.09,
		y: -347.11,
	},
	["Summoned Hydra"]: {
		baseSkill: "Hydra",
		connections: [ "Enhanced Hydra" ],
		description: `Hydra also Burns enemies for an additional {c_number}[{SF_11}*100|%|]{/c} of its base damage dealt over {c_number}{buffduration:MOD_BURN}{/c} seconds.`,
		id: 64,
		maxPoints: 1,
		x: 698.625,
		y: -447.785,
	},
	["Ice Blades"]: {
		connections: [ "Conjuration", "Enhanced Ice Blades" ],
		description: `{c_label}Cooldown:{/c} {c_resource}[{Cooldown Time}|1|]{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat_Effect_Chance_Script_Formula_Override:16}%{/c}
{/if}Conjure ice blades for {c_number}[{SF_0}|1|]{/c} seconds that rapidly slashes enemies for {c_number}{payload:TOOLTIP_DAMAGE}{/c} damage and has a {c_number}[{SF_11} * 100|%|]{/c} chance to make them {c_important}Vulnerable{/c} for {c_number}{SF_3}{/c} seconds.`,
		id: 65,
		maxPoints: 5,
		x: -392.77,
		y: -171.33,
	},
	["Enhanced Ice Blades"]: {
		baseSkill: "Ice Blades",
		connections: [ "Ice Blades", "Summoned Ice Blades", "Invoked Ice Blades" ],
		description: `Ice Blades has a {c_number}[{SF_13} * 100|%|]{/c} increased chance to make enemies {c_important}Vulnerable{/c}.`,
		id: 66,
		maxPoints: 1,
		x: -649.14,
		y: -287.95,
	},
	["Summoned Ice Blades"]: {
		baseSkill: "Ice Blades",
		connections: [ "Enhanced Ice Blades" ],
		description: `Every time Ice Blades hits a {c_important}Vulnerable{/c} enemy, it gains {c_number}[{SF_9} * 100|%|]{/c} Attack Speed, up to {c_number}[{SF_9} * {SF_10} * 100|%|]{/c}.`,
		id: 67,
		maxPoints: 1,
		x: -899.299,
		y: -333.805,
	},
	["Invoked Ice Blades"]: {
		baseSkill: "Ice Blades",
		connections: [ "Enhanced Ice Blades" ],
		description: `Killing a {c_important}Vulnerable{/c} enemy increases your active Ice Blades' duration by {c_number}{SF_15}{/c} second.`,
		id: 68,
		maxPoints: 1,
		x: -719.095,
		y: -424.735,
	},
	["Lightning Spear"]: {
		connections: [ "Conjuration", "Enhanced Lightning Spear" ],
		description: `{c_label}Cooldown: {/c}{c_resource}[{Cooldown Time}|1|]{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat_Effect_Chance_Script_Formula_Override:17}%{/c}
{/if}Conjure a crackling spear of lightning that seeks out enemies for [{SF_2}|1|] seconds, dealing {c_number}{payload:IMPACT_DAMAGE}{/c} per hit.`,
		id: 69,
		maxPoints: 5,
		x: 3.935,
		y: 249.83,
	},
	["Enhanced Lightning Spear"]: {
		baseSkill: "Lightning Spear",
		connections: [ "Lightning Spear", "Summoned Lightning Spear", "Invoked Lightning Spear" ],
		description: `Lightning Spear has a {c_number}[{SF_11}*100|%|]{/c} increased chance to critically strike against Stunned enemies.`,
		id: 70,
		maxPoints: 1,
		x: 5.03,
		y: 439.99,
	},
	["Summoned Lightning Spear"]: {
		baseSkill: "Lightning Spear",
		connections: [ "Enhanced Lightning Spear" ],
		description: `Collecting {c_important}Crackling Energy{/c} reduces the cooldown of Lightning Spear by {c_number}[{SF_9}|1|]{/c} seconds.`,
		id: 71,
		maxPoints: 1,
		x: -127.075,
		y: 583.565,
	},
	["Invoked Lightning Spear"]: {
		baseSkill: "Lightning Spear",
		connections: [ "Enhanced Lightning Spear" ],
		description: `After critically striking, Lightning Spear has a {c_number}[{SF_10} * 100|%|]{/c} increased stacking critical strike chance for its duration.`,
		id: 72,
		maxPoints: 1,
		x: 157.525,
		y: 584.88,
	},
	["Conjuration Mastery"]: {
		connections: [ "Conjuration" ],
		description: `While you have an active {c_important}Conjuration{/c} Skill, you deal {c_number}x[{SF_0} * 100|%|]{/c} increased damage.`,
		id: 73,
		maxPoints: 3,
		x: 459.155,
		y: 235.405,
	},
	["Precision Magic"]: {
		connections: [ "Conjuration" ],
		description: `Your Lucky Hit Chance is increased by up to {c_number}[{SF_0} * 100|%|]{/c}.`,
		id: 74,
		maxPoints: 3,
		x: 4.345,
		y: -340.545,
	},
	["Align the Elements"]: {
		connections: [ "Mana Shield", "Conjuration", "Protection" ],
		description: `You gain {c_number}{SF_0}%{/c} Damage Reduction against Elites for each second you don't take damage from any of these sources, up to {c_number}{SF_1}%{/c}.`,
		id: 75,
		maxPoints: 3,
		x: 691.315,
		y: 0.835,
	},
	["Mana Shield"]: {
		connections: [ "Align the Elements" ],
		description: `Every time you spend {c_number}{SF_0}{/c} Mana, you gain {c_number}[{SF_1} * 100|%|]{/c} Damage Reduction for {c_number}{SF_2}{/c} seconds.`,
		id: 76,
		maxPoints: 3,
		x: 998.925,
		y: -101.03,
	},
	["Protection"]: {
		connections: [ "Align the Elements" ],
		description: `Using a cooldown grants {c_number}[{SF_0} * 100|%|]{/c} of your Maximum Life {c_number}([PlayerHealthMax() * SF_0]){/c} as a {c_important}Barrier{/c} for {c_number}{buffduration:BUFF_BARRIER}{/c} seconds.`,
		id: 77,
		maxPoints: 3,
		x: 1006.32,
		y: 99.545,
	},
};

sorcerer["Mastery"] = {
	["Meteor"]: {
		connections: [ "Mastery", "Enhanced Meteor" ],
		description: `{c_label}Mana Cost: {/c}{c_resource}{Resource Cost}{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat_Effect_Chance_Script_Formula_Override:27}%{/c}
{/if}Summon a meteor that strikes the target location, dealing {c_number}{payload:IMPACT_DAMAGE}{/c} damage and Burning the ground for {c_number}{payload:TOOLTIP_BURN_DAMAGE}{/c} damage over {SF_4} seconds.`,
		id: 78,
		maxPoints: 5,
		x: 380.18,
		y: 119.219,
	},
	["Enhanced Meteor"]: {
		baseSkill: "Meteor",
		connections: [ "Meteor", "Mage's Meteor", "Wizard's Meteor" ],
		description: `If Meteor hits {c_number}{SF_16}{/c} or more enemies, there is a {c_number}[{SF_24}*100|%|]{/c} chance an additional Meteor falls on the same location.`,
		id: 79,
		maxPoints: 1,
		x: 661.115,
		y: 205.714,
	},
	["Mage's Meteor"]: {
		baseSkill: "Meteor",
		connections: [ "Enhanced Meteor" ],
		description: `Meteor falls {c_number}[{SF_17}*100|%|]{/c} faster and costs {c_number}{SF_18}{/c} less Mana.`,
		id: 80,
		maxPoints: 1,
		x: 781.195,
		y: 314.158,
	},
	["Wizard's Meteor"]: {
		baseSkill: "Meteor",
		connections: [ "Enhanced Meteor" ],
		description: `Meteor’s impact Immobilizes enemies for {c_number}{buffduration:IMMOBILIZE}{/c} seconds.`,
		id: 81,
		maxPoints: 1,
		x: 913.144,
		y: 212.959,
	},
	["Blizzard"]: {
		connections: [ "Mastery", "Enhanced Blizzard" ],
		description: `{c_label}Mana Cost:{/c} {c_resource}{Resource Cost}{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat_Effect_Chance_Script_Formula_Override:22}%{/c}
{/if}Summon a frigid blizzard that deals {c_number}{dot:TOOLTIP_BLIZZARD_DOT}{/c} damage and continuously {c_important}Chills{/c} enemies for {c_number}{SF_9}%{/c} over {c_number}{SF_4}{/c} seconds.`,
		id: 82,
		maxPoints: 5,
		x: -3.215,
		y: -218.79,
	},
	["Enhanced Blizzard"]: {
		baseSkill: "Blizzard",
		connections: [ "Blizzard", "Mage's Blizzard", "Wizard's Blizzard" ],
		description: `Blizzard’s duration is increased by {c_number}{SF_13}{/c} seconds.`,
		id: 83,
		maxPoints: 1,
		x: -1.79,
		y: -379.785,
	},
	["Mage's Blizzard"]: {
		baseSkill: "Blizzard",
		connections: [ "Enhanced Blizzard" ],
		description: `Every second an enemy is in Blizzard, they take {c_number}x[{SF_14} * 100|1%|]{/c} increased damage from you, up to {c_number}x[{SF_15} * 100|%|]{/c}.`,
		id: 84,
		maxPoints: 1,
		x: -133.77,
		y: -498.589,
	},
	["Wizard's Blizzard"]: {
		baseSkill: "Blizzard",
		connections: [ "Enhanced Blizzard" ],
		description: `While you have an active Blizzard, your {c_important}Core{/c} Skills cost {c_number}[{SF_16} * 100|%|]{/c} less Mana.`,
		id: 85,
		maxPoints: 1,
		x: 131.4,
		y: -504.274,
	},
	["Ball Lightning"]: {
		connections: [ "Mastery", "Enhanced Ball Lightning" ],
		description: `{c_label}Mana Cost: {/c}{c_resource}{Resource Cost}{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat Effect Chance}%{/c}
{/if}Conjure a ball of lightning that slowly moves forward, continually zapping enemies for {c_number}{payload:BALL_AOE}{/c} damage`,
		id: 86,
		maxPoints: 5,
		x: -399.365,
		y: 2.04,
	},
	["Enhanced Ball Lightning"]: {
		baseSkill: "Ball Lightning",
		connections: [ "Ball Lightning", "Wizard's Ball Lightning", "Mage's Ball Lightning" ],
		description: `Ball Lightning deals damage {c_number}[{SF_11}*100|%|]{/c} more frequently.`,
		id: 87,
		maxPoints: 1,
		x: -735.725,
		y: 0.485,
	},
	["Wizard's Ball Lightning"]: {
		baseSkill: "Ball Lightning",
		connections: [ "Enhanced Ball Lightning" ],
		description: `If an enemy is hit at least {c_number}{SF_12}{/c} times by a cast of Ball Lightning, a {c_important}Crackling Energy{/c} is formed.`,
		id: 88,
		maxPoints: 1,
		x: -945.255,
		y: -58.66,
	},
	["Mage's Ball Lightning"]: {
		baseSkill: "Ball Lightning",
		connections: [ "Enhanced Ball Lightning" ],
		description: `Each time Ball Lightning hits an enemy, it deals {c_number}x[{SF_9}*100|%|]{/c} increased damage, up to {c_number}x[{SF_10}*100|%|]{/c}.`,
		id: 89,
		maxPoints: 1,
		x: -940.325,
		y: 63.214,
	},
	["Inner Flames"]: {
		connections: [ "Mastery", "Soulfire", "Devouring Flames" ],
		description: `Your {c_important}Pyromancy{/c} Skills deal {c_number}x[{SF_1}*100|%|]{/c} increased damage after you haven't taken damage for {c_number}{SF_0}{/c} seconds.`,
		id: 90,
		maxPoints: 3,
		x: 255.625,
		y: 316.583,
	},
	["Soulfire"]: {
		connections: [ "Inner Flames" ],
		description: `{c_important}Fireball{/c} and {c_important}Meteor{/c} have an {c_number}[{SF_0|1|}* 100|%|]{/c} increased chance to Critically Strike per enemy hit.`,
		id: 91,
		maxPoints: 3,
		x: 277.195,
		y: 524.501,
	},
	["Devouring Flames"]: {
		connections: [ "Inner Flames" ],
		description: `Your {c_important}Pyromancy{/c} Skills deal {c_number}x[{SF_0} * 100|%|]{/c} increased direct damage for each source of Burning on an enemy, up to {c_number}x[{SF_0} * {SF_1} * 100|%|]{/c}.`,
		id: 92,
		maxPoints: 3,
		x: 532.345,
		y: 474.579,
	},
	["Regenerative Conduit"]: {
		connections: [ "Static Discharge", "Shocking Impact", "Mastery" ],
		description: `{c_important}Crackling Energy{/c} restores {c_number}{SF_0}{/c} Mana upon pickup.`,
		id: 93,
		maxPoints: 3,
		x: -546.19,
		y: 219.629,
	},
	["Static Discharge"]: {
		connections: [ "Regenerative Conduit" ],
		description: `{c_label}Lucky Hit:{/c} Critical Strikes with {c_important}Shock{/c} Skills have a {c_number}[{SF_0} *100|%|]{/c} chance to form a {c_important}Crackling Energy{/c}.`,
		id: 94,
		maxPoints: 3,
		x: -747.6,
		y: 402.772,
	},
	["Shocking Impact"]: {
		connections: [ "Regenerative Conduit" ],
		description: `Every time you Stun an enemy you deal {c_number}{payload:LIGHTNING_PAYLOAD}{/c} Lightning Damage to them.`,
		id: 95,
		maxPoints: 3,
		x: -937.78,
		y: 288.748,
	},
	["Icy Veil"]: {
		connections: [ "Mastery", "Hoarfrost", "Cold Front" ],
		description: `Your {c_important}Barriers{/c} have a {c_number}[{SF_0} * 100|%|]{/c} increased duration.`,
		id: 96,
		maxPoints: 3,
		x: -512.78,
		y: -241.534,
	},
	["Hoarfrost"]: {
		connections: [ "Icy Veil" ],
		description: `You deal more damage to enemies the more {c_important}Chilled{/c} they are, up to {c_number}x[{SF_0} * 100|%|]{/c} while they are {c_important}Frozen{/c}.`,
		id: 97,
		maxPoints: 3,
		x: -674.6,
		y: -423.901,
	},
	["Cold Front"]: {
		connections: [ "Icy Veil" ],
		description: `While you have a {c_important}Barrier{/c} active, you apply {c_number}[{SF_0} * 100|%|]{/c} more {c_important}Chill{/c}.`,
		id: 98,
		maxPoints: 3,
		x: -857.805,
		y: -313.911,
	},
	["Firewall"]: {
		connections: [ "Mastery", "Enhanced Firewall" ],
		description: `{c_label}Mana Cost: {/c}{c_resource}{Resource Cost}{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat_Effect_Chance_Script_Formula_Override:20}%{/c}
{/if}Create a wall of flames that Burns enemies for {c_number}{dot:TOOLTIP_BURNING}{/c} over {c_number}{SF_0}{/c} seconds.`,
		id: 99,
		maxPoints: 5,
		x: -104.505,
		y: 231.796,
	},
	["Enhanced Firewall"]: {
		baseSkill: "Firewall",
		connections: [ "Firewall", "Wizard's Firewall", "Mage's Firewall" ],
		description: `Enemies that stand in Firewall for at least {c_number}{SF_14}{/c} seconds take {c_number}x[{SF_15}*100|%|]{/c} increased Burning damage from all sources.`,
		id: 100,
		maxPoints: 1,
		x: -191.11,
		y: 388.572,
	},
	["Wizard's Firewall"]: {
		baseSkill: "Firewall",
		connections: [ "Enhanced Firewall" ],
		description: `You deal {c_number}x[{SF_17}*100|%|]{/c} increased damage per active Firewall.`,
		id: 101,
		maxPoints: 1,
		x: -371.865,
		y: 493.621,
	},
	["Mage's Firewall"]: {
		baseSkill: "Firewall",
		connections: [ "Enhanced Firewall" ],
		description: `Each enemy standing in Firewall increases your Mana Regeneration by {c_number}[{SF_16}*100|%|]{/c}.`,
		id: 102,
		maxPoints: 1,
		x: -133.4,
		y: 525.176,
	},
};

sorcerer["Ultimate"] = {
	["Inferno"]: {
		connections: [ "Ultimate", "Prime Inferno" ],
		description: `{c_label}Cooldown: {/c}{c_resource}[{Cooldown Time}|1|]{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}[{Combat Effect Chance}*2|%|]{/c}
{/if}Ignite a roaring inferno that pulses in and out of the target area, Burning enemies for {c_number}{payload:TOOLTIP_TOTAL_DAMAGE}{/c} damage over {c_number}{SF_5}{/c} seconds, and then explodes, dealing {c_number}{payload:FINAL_EXPLOSION_DAMAGE}{/c} damage to enemies on the outer edge.`,
		id: 103,
		maxPoints: 5,
		x: 318.105,
		y: -144.186,
	},
	["Prime Inferno"]: {
		baseSkill: "Inferno",
		connections: [ "Inferno", "Supreme Inferno" ],
		description: `Enemies inside of Inferno's final explosion are Immobilized for {c_number}{buffduration:IMMOBILIZE}{/c} seconds.`,
		id: 104,
		maxPoints: 1,
		x: 490.8,
		y: -293.335,
	},
	["Supreme Inferno"]: {
		baseSkill: "Inferno",
		connections: [ "Prime Inferno" ],
		description: `Killing a Burning enemy reduces Inferno's cooldown by {c_number}{SF_14}{/c} second.`,
		id: 105,
		maxPoints: 1,
		x: 792.495,
		y: -324.078,
	},
	["Unstable Currents"]: {
		connections: [ "Prime Unstable Currents", "Ultimate" ],
		description: `{c_label}Cooldown: {/c}{c_resource}[{Cooldown Time}|1|]{/c}
Lightning surges within you for {c_number}{buffduration:CURRENTS_ACTIVE}{/c} seconds. Whenever you cast a {c_important}Lightning{/c} Skill, another random non-Basic {c_important}Lightning{/c} Skill is also cast.`,
		id: 106,
		maxPoints: 5,
		x: 314.75,
		y: 150.596,
	},
	["Prime Unstable Currents"]: {
		baseSkill: "Unstable Currents",
		connections: [ "Unstable Currents", "Supreme Unstable Currents" ],
		description: `Unstable Currents increases Attack Speed by {c_number}[{SF_1} * 100|%|]{/c} while active.`,
		id: 107,
		maxPoints: 1,
		x: 558.53,
		y: 247.643,
	},
	["Supreme Unstable Currents"]: {
		baseSkill: "Unstable Currents",
		connections: [ "Prime Unstable Currents" ],
		description: `While Unstable Currents is active, collecting {c_important}Crackling Energy{/c} increases its duration by {c_number}[{SF_4}|2|]{/c} seconds.`,
		id: 108,
		maxPoints: 1,
		x: 615.31,
		y: 372.135,
	},
	["Deep Freeze"]: {
		connections: [ "Prime Deep Freeze", "Ultimate" ],
		description: `{c_label}Cooldown: {/c}{c_resource}[{Cooldown Time}|1|]{/c}
{if:ADVANCED_TOOLTIP}{c_label}Lucky Hit Chance: {/c}{c_resource}{Combat Effect Chance}%{/c}
{/if}Encase yourself in ice, becoming {c_important}Immune{/c} for {c_number}{buffduration:BUFF_IMMUNE}{/c} seconds, continually {c_important}Chilling{/c} enemies for {c_number}{SF_6}%{/c}. When Deep Freeze ends, {c_important}Frozen{/c} enemies shatter for {c_number}{payload:FROZEN_DAMAGE}{/c}. Casting Deep Freeze again ends the effect early.`,
		id: 109,
		maxPoints: 5,
		x: -295.855,
		y: -140.251,
	},
	["Prime Deep Freeze"]: {
		baseSkill: "Deep Freeze",
		connections: [ "Deep Freeze", "Supreme Deep Freeze" ],
		description: `Gain {c_number}[{SF_14}*100|%|]{/c} of your Base Life {c_number}({Shield:BARRIER}){/c} as a {c_important}Barrier{/c} for {c_number}{SF_15}{/c} seconds for each enemy shattered by Deep Freeze.`,
		id: 110,
		maxPoints: 1,
		x: -507.53,
		y: -256.42,
	},
	["Supreme Deep Freeze"]: {
		baseSkill: "Deep Freeze",
		connections: [ "Prime Deep Freeze" ],
		description: `When Deep Freeze ends, your non-Ultimate cooldowns are reduced by {c_number}[{SF_16} * 100|%|]{/c}.`,
		id: 111,
		maxPoints: 1,
		x: -799.664,
		y: -259.82,
	},
	["Frostbite"]: {
		connections: [ "Permafrost", "Ultimate", "Icy Touch" ],
		description: `You deal {c_number}x[{SF_0} * 100|%|]{/c} more damage to {c_important}Frozen{/c} or {c_important}Vulnerable{/c} enemies, and {c_number}x[{SF_1} * 100|%|]{/c} more damage to enemies who are both {c_important}Frozen{/c} and {c_important}Vulnerable{/c}.`,
		id: 112,
		maxPoints: 3,
		x: -0.71,
		y: -295.441,
	},
	["Permafrost"]: {
		connections: [ "Frostbite", "Snap Freeze" ],
		description: `{c_important}Frost{/c} Skills deal {c_number}x[{SF_0} * 100|%|]{/c} increased damage to Elites.`,
		id: 113,
		maxPoints: 3,
		x: -146.565,
		y: -443.177,
	},
	["Snap Freeze"]: {
		connections: [ "Permafrost", "Icy Touch" ],
		description: `{c_label}Lucky Hit:{/c} {c_important}Frost{/c} Skills have up to a {c_number}{SF_0}%{/c} chance to instantly {c_important}Freeze{/c}.`,
		id: 114,
		maxPoints: 3,
		x: -1.96,
		y: -586.799,
	},
	["Icy Touch"]: {
		connections: [ "Frostbite", "Snap Freeze" ],
		description: `You deal {c_number}x[{SF_0} * 100|%|]{/c} increased damage to {c_important}Vulnerable{/c} enemies.`,
		id: 115,
		maxPoints: 3,
		x: 135.1,
		y: -439.918,
	},
	["Coursing Currents"]: {
		connections: [ "Electrocution", "Conduction", "Ultimate" ],
		description: `Hitting enemies with {c_important}Shock{/c} Skills increases your Critical Strike Chance by {c_number}[{SF_1} * 100|%|]{/c}. Resets upon getting a Critical Strike.`,
		id: 116,
		maxPoints: 3,
		x: 14.79,
		y: 281.384,
	},
	["Electrocution"]: {
		connections: [ "Coursing Currents", "Convulsions" ],
		description: `Enemies deal {c_number}[{SF_0}*100|%|]{/c} less damage for {c_number}{buffduration:BUFF_DAMAGE_PENALITY}{/c} seconds after being Critically Struck by your {c_important}Shock{/c} Skills.`,
		id: 117,
		maxPoints: 3,
		x: 174.065,
		y: 429.587,
	},
	["Convulsions"]: {
		connections: [ "Conduction", "Electrocution" ],
		description: `{c_label}Lucky Hit:{/c} {c_important}Shock{/c} Skills have up to a {c_number}[{SF_0}|%|]{/c} chance to Stun enemies for {c_number}{SF_1}{/c} seconds.`,
		id: 118,
		maxPoints: 3,
		x: 24.29,
		y: 587.361,
	},
	["Conduction"]: {
		connections: [ "Coursing Currents", "Convulsions" ],
		description: `Critical Strikes with {c_important}Shock{/c} Skills increase your Attack Speed by {c_number}[{SF_0} * 100|%|]{/c} for {c_number}{SF_1}{/c} seconds.`,
		id: 119,
		maxPoints: 3,
		x: -125.19,
		y: 431.627,
	},
	["Immolated Flesh"]: {
		connections: [ "Endless Pyre", "Fiery Surge", "Ultimate" ],
		description: `Burning enemies deal {c_number}[{SF_0}*100|1%|]{/c} reduced damage.`,
		id: 120,
		maxPoints: 3,
		x: 566.69,
		y: 0.646,
	},
	["Endless Pyre"]: {
		connections: [ "Pyromania", "Immolated Flesh" ],
		description: `Burning effects last {c_number}[{SF_0}*100|%|]{/c} longer.`,
		id: 121,
		maxPoints: 3,
		x: 832.9,
		y: 75.957,
	},
	["Pyromania"]: {
		connections: [ "Fiery Surge", "Endless Pyre" ],
		description: `You deal {c_number}x[{SF_0} * 100|%|]{/c} increased Critical Strike Damage per Nearby Burning enemy, up to {c_number}x[{SF_2} * 100|%|]{/c}.`,
		id: 122,
		maxPoints: 3,
		x: 1088.14,
		y: 0.014,
	},
	["Fiery Surge"]: {
		connections: [ "Pyromania", "Immolated Flesh" ],
		description: `Killing a Burning enemy grants {c_number}[{SF_0} * 100|%|]{/c} Attack Speed for {c_number}{buffduration:ATTACK_SPEED_BONUS}{/c} seconds.`,
		id: 123,
		maxPoints: 3,
		x: 822.8,
		y: -87.71,
	},
};

sorcerer["Capstone"] = {
	["Shatter"]: {
		connections: [ "Capstone" ],
		description: `After {c_important}Freeze{/c} expires, enemies explode for {c_number}[{SF_0} * 100|%|]{/c} of the damage you dealt to them while {c_important}Frozen{/c}.`,
		id: 124,
		maxPoints: 1,
		x: -562.921,
		y: 368.895,
	},
	["Icefall"]: {
		connections: [ "Capstone" ],
		description: `{c_label}Lucky Hit:{/c} Your {c_important}Frost{/c} Skills have up to a {c_number}[{SF_0} * 100|%|]{/c} chance to make your next {c_important}Ice Shards{/c}, {c_important}Frozen Orb{/c}, or {c_important}Blizzard{/c} consume no Mana and deal {c_number}x[{SF_1} * 100|%|]{/if}{/c} more damage. Chance is doubled against {c_important}Vulnerable{/c} enemies.`,
		id: 125,
		maxPoints: 1,
		x: -917.155,
		y: 368.385,
	},
	["Warmth"]: {
		connections: [ "Capstone" ],
		description: `{c_label}Lucky Hit:{/c} Up to a {c_number}{SF_1}%{/c} chance to gain {c_number}{SF_0}{/c} Mana per source of Burning on the enemy.`,
		id: 126,
		maxPoints: 1,
		x: 498.261,
		y: 369.695,
	},
	["Esu's Ferocity"]: {
		connections: [ "Capstone" ],
		description: `You deal {c_number}x[{SF_1}*100|%|]{/c} increased Burning damage to enemies over {c_number}[{SF_2}*100|%|]{/c} Life and {c_number}x[{SF_0}*100|%|]{/c} increased {c_important}Pyromancy{/c} Skill Direct Damage to enemies under {c_number}[{SF_2}*100|%|]{/c} Life.`,
		id: 127,
		maxPoints: 1,
		x: 880.17,
		y: 371.42,
	},
	["Overflowing Energy"]: {
		connections: [ "Capstone" ],
		description: `{c_important}Crackling Energy{/c} hits {c_number}{SF_0}{/c} additional enemy. Each time {c_important}Crackling Energy{/c} hits an enemy, your {c_important}Shock{/c} Skill cooldowns are reduced by {c_number}[{SF_1}|1|]{/c} seconds, increased to {c_number}[{SF_2}|2|]{/c} seconds against Elites.`,
		id: 128,
		maxPoints: 1,
		x: -200.689,
		y: 364.71,
	},
	["Vyr's Mastery"]: {
		connections: [ "Capstone" ],
		description: `Close enemies take {c_number}x[{SF_1}*100|%|]{/c} more damage from your {c_important}Shock{/c} Skills and deal {c_number}x[{SF_3} * 100|%|]{/c} less damage to you.`,
		id: 129,
		maxPoints: 1,
		x: 150.695,
		y: 368.055,
	},
};

export { sorcerer };