let codexHistory = {
	"Defensive: Aspect of the Deflecting Barrier": 0,
	"Defensive: Aspect of Disobedience": 1,
	"Defensive: Aspect of Might": 2,
	"Defensive: Protecting Aspect": 3,
	"Defensive: Aspect of the Protector": 4,
	"Offensive: Edgemaster's Aspect": 5,
	"Offensive: Aspect of the Expectant": 6,
	"Offensive: Aspect of Inner Calm": 7,
	"Offensive: Needleflare Aspect": 8,
	"Offensive: Aspect of Pummeling": 9,
	"Offensive: Rapid Aspect": 10,
	"Offensive: Aspect of Retribution": 11,
	"Resource: Aspect of the Umbral": 12,
	"Utility: Aspect of Shared Misery": 13,
	"Mobility: Ghostwalker Aspect": 14,
	"Mobility: Wind Striker Aspect": 15,
	"Defensive: Aspect of Bul-Kathos": 16,
	"Defensive: Aspect of the Iron Warrior": 17,
	"Defensive: Aspect of Numbing Wrath": 18,
	"Defensive: Aspect of Tempering Blows": 19,
	"Offensive: Aspect of Ancestral Echoes": 20,
	"Offensive: Aspect of Ancestral Force": 21,
	"Offensive: Aspect of Berserk Ripping": 22,
	"Offensive: Brawler's Aspect": 23,
	"Offensive: Death Wish Aspect": 24,
	"Offensive: Aspect of the Dire Whirlwind": 25,
	"Offensive: Aspect of Quickening Pulse": 26,
	"Offensive: Veteran Brawler's Aspect": 27,
	"Offensive: Windstriker's Aspect": 28,
	"Resource: Aspect of Echoing Fury": 29,
	"Resource: Aspect of the Relentless Armsmaster": 30,
	"Resource: Slaking Aspect": 31,
	"Resource: Aspect of Unrelenting Fury": 32,
	"Utility: Aspect of Anemia": 33,
	"Utility: Relentless Berserker's Aspect": 34,
	"Mobility: Aspect of Perpetual Stomping": 35,
	"Defensive: Aspect of Cyclonic Force": 36,
	"Defensive: Aspect of Mending Stone": 37,
	"Defensive: Skinwalker's Aspect": 38,
	"Defensive: Stalking Beast Aspect": 39,
	"Defensive: Vigorous Aspect": 40,
	"Offensive: Crashstone Aspect": 41,
	"Offensive: Nighthowler's Aspect": 42,
	"Offensive: Overcharged Aspect": 43,
	"Offensive: Aspect of the Rampaging Werebeast": 44,
	"Offensive: Aspect of Retaliation": 45,
	"Offensive: Shepherd's Aspect": 46,
	"Offensive: Aspect of the Tempest": 47,
	"Offensive: Aspect of the Ursine Horror": 48,
	"Resource: Aspect of the Changeling's Debt": 49,
	"Resource: Mangled Aspect": 50,
	"Resource: Storm Beast's Aspect": 51,
	"Resource: Aspect of the Unsatiated": 52,
	"Utility: Ballistic Aspect": 53,
	"Utility: Aspect of Quicksand": 54,
	"Utility: Stormshifter's Aspect": 55,
	"Defensive: Aspect of Grasping Veins": 56,
	"Offensive: Blighted Aspect": 57,
	"Offensive: Blood-bathed Aspect": 58,
	"Offensive: Blood Seeker's Aspect": 59,
	"Offensive: Aspect of Bursting Bones": 60,
	"Offensive: Aspect of the Damned": 61,
	"Offensive: Aspect of Empowering Reaper": 62,
	"Offensive: Aspect of Possessed Blood": 63,
	"Offensive: Aspect of Reanimation": 64,
	"Offensive: Sacrificial Aspect": 65,
	"Offensive: Aspect of Swelling Curse": 66,
	"Offensive: Unyielding Commander's Aspect": 67,
	"Resource: Fastblood Aspect": 68,
	"Resource: Flesh-Rending Aspect": 69,
	"Resource: Hulking Aspect": 70,
	"Resource: Aspect of Potent Blood": 71,
	"Resource: Requiem Aspect": 72,
	"Utility: Aspect of Torment": 73,
	"Utility: Torturous Aspect": 74,
	"Utility: Aspect of the Void": 75,
	"Defensive: Cheat's Aspect": 76,
	"Defensive: Enshrouding Aspect": 77,
	"Defensive: Aspect of Siphoned Protection": 78,
	"Defensive: Aspect of Uncanny Resilience": 79,
	"Offensive: Aspect of Arrow Storms": 80,
	"Offensive: Blast-Trapper's Aspect": 81,
	"Offensive: Aspect of Branching Volleys": 82,
	"Offensive: Aspect of Corruption": 83,
	"Offensive: Aspect of Encircling Blades": 84,
	"Offensive: Opportunist's Aspect": 85,
	"Offensive: Shadowslicer Aspect": 86,
	"Offensive: Aspect of Sleeting Imbuements": 87,
	"Offensive: Trickster's Aspect": 88,
	"Offensive: Aspect of Unstable Imbuements": 89,
	"Offensive: Vengeful Aspect": 90,
	"Offensive: Aspect of Volatile Blades": 91,
	"Offensive: Aspect of Volatile Shadows": 92,
	"Resource: Energizing Aspect": 93,
	"Resource: Ravenous Aspect": 94,
	"Utility: Aspect of Explosive Verve": 95,
	"Defensive: Snowguard's Aspect": 96,
	"Defensive: Snowveiled Aspect": 97,
	"Defensive: Aspect of the Unwavering": 98,
	"Offensive: Aspect of Biting Cold": 99,
	"Offensive: Aspect of Conflagration": 100,
	"Offensive: Aspect of Control": 101,
	"Offensive: Elementalist's Aspect": 102,
	"Offensive: Aspect of Overwhelming Bolts": 103,
	"Offensive: Aspect of Piercing Cold": 104,
	"Offensive: Rolling Thunder Aspect": 105,
	"Offensive: Aspect of Splintering Energy": 106,
	"Offensive: Storm Swell Aspect": 107,
	"Offensive: Aspect of Three Curses": 108,
	"Resource: Aspect of Efficiency": 109,
	"Resource: Incendiary Aspect": 110,
	"Resource: Prodigy's Aspect": 111,
	"Resource: Recharging Aspect": 112,
	"Utility: Aspect of Seared Flesh": 113,
	"Mobility: Aspect of the Bounding Conduit": 114,
	"Mobility: Charged Aspect": 115,
	"Mobility: Flamewalker's Aspect": 116,
	"Offensive: Aspect of Burning Rage": 117,
	"Offensive: Devilish Aspect": 118,
	"Offensive: Aspect of Limitless Rage": 119,
	"Offensive: Earthquake Aspect": 120,
	"Offensive: Skullbreaker's Aspect": 121,
	"Utility: Weapon Master's Aspect": 122,
	"Defensive: Iron Blood Aspect": 123,
	"Other: Battle-Mad Aspect": 124,
	"Resource: Aspect of Giant Strides": 125,
	"Offensive: Dust Devil's Aspect": 126,
	"Offensive: Aspect of Encroaching Wrath": 127,
	"Resource: Aspect of Berserk Fury": 128,
	"Offensive: Windlasher Aspect": 129,
	"Utility: Aspect of Grasping Whirlwind": 130,
	"Defensive: Steadfast Berserker's Aspect": 131,
	"Resource: Bold Chieftain's Aspect": 132,
	"Offensive: Earthstriker's Aspect": 133,
	"Utility: Luckbringer Aspect": 134,
	"Resource: Bear Clan Berserker's Aspect": 135,
	"Other: Ramaladni's Magnum Opus": 136,
	"Offensive: Ancients' Oath": 137,
	"Offensive: Hellhammer": 138,
	"Offensive: Overkill": 139,
	"Other: Fields of Crimson": 140,
	"Offensive: Battle Trance": 141,
	"Offensive: 100,000 Steps": 142,
	"Offensive: Rage of Harrogath": 143,
	"Offensive: Gohr's Devastating Grips": 144,
	"Offensive: Lightning Dancer's Aspect": 145,
	"Offensive: Dire Wolf's Aspect": 146,
	"Offensive: Aspect of the Stampede": 147,
	"Offensive: Aspect of Metamorphic Stone": 148,
	"Offensive: Aspect of the Blurred Beast": 149,
	"Resource: Aspect of the Calm Breeze": 150,
	"Offensive: Aspect of Natural Balance": 151,
	"Offensive: Seismic-shift Aspect": 152,
	"Offensive: Aspect of the Trampled Earth": 153,
	"Offensive: Stormclaw's Aspect": 154,
	"Resource: Balanced Aspect": 155,
	"Offensive: Aspect of The Aftershock": 156,
	"Offensive: Shockwave Aspect": 157,
	"Offensive: Aspect of the Alpha": 158,
	"Offensive: Aspect of Nature's Savagery": 159,
	"Utility: Aspect of the Dark Howl": 160,
	"Offensive: Aspect of the Wildrage": 161,
	"Offensive: Stormchaser's Aspect": 162,
	"Offensive: Runeworker's Conduit Aspect": 163,
	"Offensive: Mighty Storm's Aspect": 164,
	"Utility: Symbiotic Aspect": 165,
	"Defensive: Earthguard Aspect": 166,
	"Defensive: Waxing Gibbous": 167,
	"Offensive: Greatstaff of the Crone": 168,
	"Offensive: Mad Wolf's Glee": 169,
	"Offensive: Insatiable Fury": 170,
	"Resource: Tempest Roar": 171,
	"Defensive: Vasily's Prayer": 172,
	"Offensive: Storm's Companion": 173,
	"Offensive: Hunter's Zenith": 174,
	"Offensive: Accelerating Aspect": 175,
	"Utility: Exploiter's Aspect": 176,
	"Resource: Starlight Aspect": 177,
	"Offensive: Conceited Aspect": 178,
	"Defensive: Aspect of the Crowded Sage": 179,
	"Utility: Eluding Aspect": 180,
	"Resource: Assimilation Aspect": 181,
	"Offensive: Smiting Aspect": 182,
	"Offensive: The Butcher's Cleaver": 183,
	"Offensive: Doombringer": 184,
	"Offensive: The Grandfather": 185,
	"Utility: Melted Heart of Selig": 186,
	"Utility: Penitent Greaves": 187,
	"Offensive: Razorplate": 188,
	"Offensive: Fists of Fate": 189,
	"Utility: Frostburn": 190,
	"Offensive: Andariel's Visage": 191,
	"Utility: Harlequin Crest": 192,
	"Defensive: Temerity": 193,
	"Resource: Mother's Embrace": 194,
	"Resource: Ring of Starless Skies": 195,
	"Offensive: Aspect of Ultimate Shadow": 196,
	"Offensive: Aspect of Explosive Mist": 197,
	"Offensive: Aspect of Frenzied Dead": 198,
	"Offensive: Splintering Aspect": 199,
	"Offensive: Aspect of Plunging Darkness": 200,
	"Offensive: Rotting Aspect": 201,
	"Utility: Coldbringer's Aspect": 202,
	"Offensive: Aspect of Hungry Blood": 203,
	"Utility: Viscous Aspect": 204,
	"Offensive: Blood-soaked Aspect": 205,
	"Defensive: Aspect of Shielding Storm": 206,
	"Offensive: Aspect of Grasping Veins": 207,
	"Utility: Blood Getter's Aspect": 208,
	"Resource: Aspect of Torment": 209,
	"Offensive: Aspect of Serration": 210,
	"Offensive: Osseous Gale Aspect": 211,
	"Resource: Aspect of Exposed Flesh": 212,
	"Offensive: Aspect of Decay": 213,
	"Offensive: Tidal Aspect": 214,
	"Offensive: Aspect of Rathma's Chosen": 215,
	"Offensive: Aspect of Untimely Death": 216,
	"Defensive: Aspect of Hardened Bones": 217,
	"Offensive: Cadaverous Aspect": 218,
	"Defensive: Aspect of the Embalmer": 219,
	"Offensive: Black River": 220,
	"Utility: Bloodless Scream": 221,
	"Offensive: Deathspeaker's Pendant": 222,
	"Offensive: Greaves of the Empty Tomb": 223,
	"Offensive: Blood Artisan's Cuirass": 224,
	"Offensive: Howl from Below": 225,
	"Offensive: Deathless Visage": 226,
	"Offensive: Ring of Mendeln": 227,
	"Offensive: Repeating Aspect": 228,
	"Defensive: Snap Frozen Aspect": 229,
	"Offensive: Aspect of Imitated Imbuement": 230,
	"Offensive: Trickshot Aspect": 231,
	"Offensive: Aspect of Surprise": 232,
	"Offensive: Bladedancer's Aspect": 233,
	"Offensive: Toxic Alchemist's Aspect": 234,
	"Offensive: Icy Alchemist's Aspect": 235,
	"Offensive: Aspect of Bursting Venoms": 236,
	"Defensive: Aspect of Uncanny Treachery": 237,
	"Defensive: Aspect of Cruel Sustenance": 238,
	"Defensive: Escape Artist's Aspect": 239,
	"Defensive: Aspect of Stolen Vigor": 240,
	"Utility: Aspect of Quickening Fog": 241,
	"Defensive: Aspect of Siphoned Victuals": 242,
	"Utility: Mangler's Aspect": 243,
	"Defensive: Umbrous Aspect": 244,
	"Utility: Aspect of Noxious Ice": 245,
	"Mobility: Ravager's Aspect": 246,
	"Offensive: Aspect of Synergy": 247,
	"Defensive: Aspect of Lethal Dusk": 248,
	"Defensive: Aspect of Elusive Menace": 249,
	"Offensive: Infiltrator's Aspect": 250,
	"Utility: Frostbitten Aspect": 251,
	"Offensive: Condemnation": 252,
	"Other: Asheara's Khanjar": 253,
	"Offensive: Skyhunter": 254,
	"Offensive: Windforce": 255,
	"Offensive: Word of Hakan": 256,
	"Offensive: Grasp of Shadow": 257,
	"Offensive: Cowl of the Nameless": 258,
	"Utility: Eyes in the Dark": 259,
	"Offensive: Aspect of Frozen Memories": 260,
	"Offensive: Aspect of Abundant Energy": 261,
	"Offensive: Shattered Aspect": 262,
	"Utility: Aspect of Binding Embers": 263,
	"Offensive: Aspect of Static Cling": 264,
	"Defensive: Frostblitz Aspect": 265,
	"Offensive: Aspect of Frozen Orbit": 266,
	"Offensive: Serpentine Aspect": 267,
	"Offensive: Aspect of Armageddon": 268,
	"Offensive: Aspect of Ancient Flame": 269,
	"Offensive: Aspect of Engulfing Flames": 270,
	"Utility: Aspect of Singed Extremities": 271,
	"Offensive: Aspect of Shattered Stars": 272,
	"Offensive: Glacial Aspect": 273,
	"Offensive: Aspect of the Frozen Wake": 274,
	"Defensive: Encased Aspect": 275,
	"Utility: Aspect of Fortune": 276,
	"Offensive: Aspect of the Frozen Tundra": 277,
	"Offensive: Aspect of Overwhelming Currents": 278,
	"Offensive: Gravitational Aspect": 279,
	"Offensive: Mage-Lord's Aspect": 280,
	"Offensive: Aspect of the Unbroken Tether": 281,
	"Offensive: Stable Aspect": 282,
	"Resource: Aspect of Concentration": 283,
	"Defensive: Everliving Aspect": 284,
	"Offensive: Flamescar": 285,
	"Offensive: Staff of Endless Rage": 286,
	"Offensive: Staff of Lam Esen": 287,
	"Offensive: Esadora's Overflowing Cameo": 288,
	"Offensive: Esu's Heirloom": 289,
	"Utility: Raiment of the Infinite": 290,
	"Offensive: Gloves of the Illuminator": 291,
	"Defensive: Iceheart Brais": 292
}

export { codexHistory };