let codexHistory = {
	"Defensive: Aspect of the Deflecting Barrier": 0,
	"Defensive: Aspect of Disobedience": 1,
	"Defensive: Aspect of Might": 2,
	"Defensive: Protecting Aspect": 3,
	"Defensive: Aspect of the Protector": 4,
	"Offensive: Edgemaster's Aspect": 5,
	"Offensive: Aspect of the Expectant": 6,
	"Offensive: Aspect of Inner Calm": 7,
	"Offensive: Needleflare Aspect": 8,
	"Offensive: Aspect of Pummeling": 9,
	"Offensive: Rapid Aspect": 10,
	"Offensive: Aspect of Retribution": 11,
	"Resource: Aspect of the Umbral": 12,
	"Utility: Aspect of Shared Misery": 13,
	"Mobility: Ghostwalker Aspect": 14,
	"Mobility: Wind Striker Aspect": 15,
	"Defensive: Aspect of Bul-Kathos": 16,
	"Defensive: Aspect of the Iron Warrior": 17,
	"Defensive: Aspect of Numbing Wrath": 18,
	"Defensive: Aspect of Tempering Blows": 19,
	"Offensive: Aspect of Ancestral Echoes": 20,
	"Offensive: Aspect of Ancestral Force": 21,
	"Offensive: Aspect of Berserk Ripping": 22,
	"Offensive: Brawler's Aspect": 23,
	"Offensive: Death Wish Aspect": 24,
	"Offensive: Aspect of the Dire Whirlwind": 25,
	"Offensive: Aspect of Quickening Pulse": 26,
	"Offensive: Veteran Brawler's Aspect": 27,
	"Offensive: Windstriker's Aspect": 28,
	"Resource: Aspect of Echoing Fury": 29,
	"Resource: Aspect of the Relentless Armsmaster": 30,
	"Resource: Slaking Aspect": 31,
	"Resource: Aspect of Unrelenting Fury": 32,
	"Utility: Aspect of Anemia": 33,
	"Utility: Relentless Berserker's Aspect": 34,
	"Mobility: Aspect of Perpetual Stomping": 35,
	"Defensive: Aspect of Cyclonic Force": 36,
	"Defensive: Aspect of Mending Stone": 37,
	"Defensive: Skinwalker's Aspect": 38,
	"Defensive: Stalking Beast Aspect": 39,
	"Defensive: Vigorous Aspect": 40,
	"Offensive: Crashstone Aspect": 41,
	"Offensive: Nighthowler's Aspect": 42,
	"Offensive: Overcharged Aspect": 43,
	"Offensive: Aspect of the Rampaging Werebeast": 44,
	"Offensive: Aspect of Retaliation": 45,
	"Offensive: Shepherd's Aspect": 46,
	"Offensive: Aspect of the Tempest": 47,
	"Offensive: Aspect of the Ursine Horror": 48,
	"Resource: Aspect of the Changeling's Debt": 49,
	"Resource: Mangled Aspect": 50,
	"Resource: Storm Beast's Aspect": 51,
	"Resource: Aspect of the Unsatiated": 52,
	"Utility: Ballistic Aspect": 53,
	"Utility: Aspect of Quicksand": 54,
	"Utility: Stormshifter's Aspect": 55,
	"Defensive: Aspect of Grasping Veins": 56,
	"Offensive: Blighted Aspect": 57,
	"Offensive: Blood-bathed Aspect": 58,
	"Offensive: Blood Seeker's Aspect": 59,
	"Offensive: Aspect of Bursting Bones": 60,
	"Offensive: Aspect of the Damned": 61,
	"Offensive: Aspect of Empowering Reaper": 62,
	"Offensive: Aspect of Possessed Blood": 63,
	"Offensive: Aspect of Reanimation": 64,
	"Offensive: Sacrificial Aspect": 65,
	"Offensive: Aspect of Swelling Curse": 66,
	"Offensive: Unyielding Commander's Aspect": 67,
	"Resource: Fastblood Aspect": 68,
	"Resource: Flesh-Rending Aspect": 69,
	"Resource: Hulking Aspect": 70,
	"Resource: Aspect of Potent Blood": 71,
	"Resource: Requiem Aspect": 72,
	"Utility: Aspect of Torment": 73,
	"Utility: Torturous Aspect": 74,
	"Utility: Aspect of the Void": 75,
	"Defensive: Cheat's Aspect": 76,
	"Defensive: Enshrouding Aspect": 77,
	"Defensive: Aspect of Siphoned Protection": 78,
	"Defensive: Aspect of Uncanny Resilience": 79,
	"Offensive: Aspect of Arrow Storms": 80,
	"Offensive: Blast-Trapper's Aspect": 81,
	"Offensive: Aspect of Branching Volleys": 82,
	"Offensive: Aspect of Corruption": 83,
	"Offensive: Aspect of Encircling Blades": 84,
	"Offensive: Opportunist's Aspect": 85,
	"Offensive: Shadowslicer Aspect": 86,
	"Offensive: Aspect of Sleeting Imbuements": 87,
	"Offensive: Trickster's Aspect": 88,
	"Offensive: Aspect of Unstable Imbuements": 89,
	"Offensive: Vengeful Aspect": 90,
	"Offensive: Aspect of Volatile Blades": 91,
	"Offensive: Aspect of Volatile Shadows": 92,
	"Resource: Energizing Aspect": 93,
	"Resource: Ravenous Aspect": 94,
	"Utility: Aspect of Explosive Verve": 95,
	"Defensive: Snowguard's Aspect": 96,
	"Defensive: Snowveiled Aspect": 97,
	"Defensive: Aspect of the Unwavering": 98,
	"Offensive: Aspect of Biting Cold": 99,
	"Offensive: Aspect of Conflagration": 100,
	"Offensive: Aspect of Control": 101,
	"Offensive: Elementalist's Aspect": 102,
	"Offensive: Aspect of Overwhelming Bolts": 103,
	"Offensive: Aspect of Piercing Cold": 104,
	"Offensive: Rolling Thunder Aspect": 105,
	"Offensive: Aspect of Splintering Energy": 106,
	"Offensive: Storm Swell Aspect": 107,
	"Offensive: Aspect of Three Curses": 108,
	"Resource: Aspect of Efficiency": 109,
	"Resource: Incendiary Aspect": 110,
	"Resource: Prodigy's Aspect": 111,
	"Resource: Recharging Aspect": 112,
	"Utility: Aspect of Seared Flesh": 113,
	"Mobility: Aspect of the Bounding Conduit": 114,
	"Mobility: Charged Aspect": 115,
	"Mobility: Flamewalker's Aspect": 116
}

export { codexHistory };